name: Hello World CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t atlantis-terragrunt .
      - name: Tags
        run: |
          docker tag atlantis-terragrunt ${{ secrets.DOCKER_USER }}/atlantis-terragrunt:${{ github.sha }}
          docker tag atlantis-terragrunt ${{ secrets.DOCKER_USER }}/atlantis-terragrunt:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/atlantis-terragrunt:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/atlantis-terragrunt:latest